### ISSUE TITLE
Crash in release build

### ISSUE THREAD

**Issue by rprouse** [rprouse/HamRadioStudy#28]
Release builds crash after hitting the TX button on the main page before navigating to the quiz.

Logs from ADB

```txt
03-17 17:43:18.691  4113  4113 E AndroidRuntime: FATAL EXCEPTION: main
03-17 17:43:18.691  4113  4113 E AndroidRuntime: Process: net.alteridem.hamradiostudy, PID: 4113
03-17 17:43:18.691  4113  4113 E AndroidRuntime: android.runtime.JavaProxyThrowable: [System.Reflection.TargetInvocationException]: Arg_TargetInvocationException
03-17 17:43:18.691  4113  4113 E AndroidRuntime:        at System.Reflection.MethodBaseInvoker.InvokeDirectByRefWithFewArgs(Unknown Source:0)
03-17 17:43:18.691  4113  4113 E AndroidRuntime:        at System.Reflection.MethodBaseInvoker.InvokeWithOneArg(Unknown Source:0)
03-17 17:43:18.691  4113  4113 E AndroidRuntime:        at System.Reflection.RuntimeConstructorInfo.Invoke(Unknown Source:0)
03-17 17:43:18.691  4113  4113 E AndroidRuntime:        at System.RuntimeType.CreateInstanceImpl(Unknown Source:0)
03-17 17:43:18.691  4113  4113 E AndroidRuntime:        at System.Activator.CreateInstance(Unknown Source:0)
03-17 17:43:18.691  4113  4113 E AndroidRuntime:        at System.Activator.CreateInstance(Unknown Source:0)
03-17 17:43:18.691  4113  4113 E AndroidRuntime:        at HamRadioStudy.Services.NavigationService+<NavigateToAsync>d__0.MoveNext(Unknown Source:0)
03-17 17:43:18.691  4113  4113 E AndroidRuntime:        at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Unknown Source:0)
03-17 17:43:18.691  4113  4113 E AndroidRuntime:        at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Unknown Source:0)
03-17 17:43:18.691  4113  4113 E AndroidRuntime:        at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Unknown Source:0)
03-17 17:43:18.691  4113  4113 E AndroidRuntime:        at HamRadioStudy.ViewModels.MainPageViewModel+<<get_TakeQuizCommand>b__13_0>d.MoveNext(Unknown Source:0)
03-17 17:43:18.691  4113  4113 E AndroidRuntime:        at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Unknown Source:0)
03-17 17:43:18.691  4113  4113 E AndroidRuntime:        at System.Threading.Tasks.Task+<>c.<ThrowAsync>b__128_0(Unknown Source:0)
03-17 17:43:18.691  4113  4113 E AndroidRuntime:        at Android.App.SyncContext+<>c__DisplayClass2_0.<Post>b__0(Unknown Source:0)
03-17 17:43:18.691  4113  4113 E AndroidRuntime:        at Java.Lang.Thread+RunnableImplementor.Run(Unknown Source:0)
03-17 17:43:18.691  4113  4113 E AndroidRuntime:        at Java.Lang.IRunnableInvoker.n_Run(Unknown Source:0)
03-17 17:43:18.691  4113  4113 E AndroidRuntime:        at Android.Runtime.JNINativeWrapper.Wrap_JniMarshal_PP_V(Unknown Source:0)
03-17 17:43:18.691  4113  4113 E AndroidRuntime:        at mono.java.lang.RunnableImplementor.n_run(Native Method)
03-17 17:43:18.691  4113  4113 E AndroidRuntime:        at mono.java.lang.RunnableImplementor.run(RunnableImplementor.java:31)
03-17 17:43:18.691  4113  4113 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:958)
03-17 17:43:18.691  4113  4113 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:99)
03-17 17:43:18.691  4113  4113 E AndroidRuntime:        at android.os.Looper.loopOnce(Looper.java:205)
03-17 17:43:18.691  4113  4113 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:294)
03-17 17:43:18.691  4113  4113 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:8177)
03-17 17:43:18.691  4113  4113 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
03-17 17:43:18.691  4113  4113 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
03-17 17:43:18.691  4113  4113 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
```

Callstack of interest seems to be the `CreateInstance` in `NavigateAsync`

```txt
at System.Activator.CreateInstance(Unknown Source:0)
at HamRadioStudy.Services.NavigationService+<NavigateToAsync>d__0.MoveNext(Unknown Source:0)
```

**Comment by rprouse** [comment]
Created a very simple page with an empty view model to see if it an issue with the navigation or with the page that is being created. Still happens, so it isn't the QuestionsPage or the constructor. It is therefore a problem with the navigate code itself.

**Comment by rprouse** [comment]
That may not be correct, Statistics uses the same navigation call.

**Comment by rprouse** [comment]
By adding try/catches, I've tracked it down to the constructor of QuestionsPage,

![image](https://github.com/rprouse/HamRadioStudy/assets/493828/62ade71b-797c-4283-add0-ec022c21b273)

**Comment by rprouse** [comment]
![image](https://github.com/rprouse/HamRadioStudy/assets/493828/1a11a6b5-fdf1-4b35-a936-fba4513b0cab)

**Comment by rprouse** [comment]
It turns out that the issue is the binding to an item in an array like `Text="{Binding Answers[0]}"`, so switching to use properties pointing at each array item instead. See https://github.com/dotnet/maui/issues/9697
